spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@spb:1521/XEPDB1
    username: rep
    password: rep
    hikari:
      maximum-pool-size: 5
      minimum-idle: 4
      data-source-properties:
        oracle:
          jdbc:
            defaultConnectionValidation: local
  main:
    banner-mode: off
#logging:
#  level.org.springframework=ERROR
#  level.org.example.bybit=INFO
