server:
  port: 8087
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
    metrics:
      tags:
        application: adminServer
      export:
        prometheus:
          enabled: true
    prometheus:
      enabled=true:
